# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_server.proto',
  package='message_server_api',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14message_server.proto\x12\x12message_server_api\"5\n\x17register_client_request\x12\x1a\n\x12prefered_client_id\x18\x01 \x01(\t\"-\n\x18register_client_response\x12\x11\n\tclient_id\x18\x01 \x01(\t\"6\n\x13\x61\x64\x64_message_request\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"*\n\x14\x61\x64\x64_message_response\x12\x12\n\nmessage_id\x18\x01 \x01(\x04\"I\n\x14poll_message_request\x12\x1e\n\x16last_polled_message_id\x18\x01 \x01(\x04\x12\x11\n\tclient_id\x18\x02 \x01(\t\"L\n\x15poll_message_response\x12\x0c\n\x04text\x18\x01 \x03(\t\x12\x12\n\nmessage_id\x18\x02 \x03(\x04\x12\x11\n\tclient_id\x18\x03 \x03(\t2\xc4\x02\n\x07storage\x12\x62\n\x0b\x61\x64\x64_message\x12\'.message_server_api.add_message_request\x1a(.message_server_api.add_message_response\"\x00\x12\x65\n\x0cpoll_message\x12(.message_server_api.poll_message_request\x1a).message_server_api.poll_message_response\"\x00\x12n\n\x0fregister_client\x12+.message_server_api.register_client_request\x1a,.message_server_api.register_client_response\"\x00\x62\x06proto3'
)




_REGISTER_CLIENT_REQUEST = _descriptor.Descriptor(
  name='register_client_request',
  full_name='message_server_api.register_client_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='prefered_client_id', full_name='message_server_api.register_client_request.prefered_client_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=97,
)


_REGISTER_CLIENT_RESPONSE = _descriptor.Descriptor(
  name='register_client_response',
  full_name='message_server_api.register_client_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='message_server_api.register_client_response.client_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=144,
)


_ADD_MESSAGE_REQUEST = _descriptor.Descriptor(
  name='add_message_request',
  full_name='message_server_api.add_message_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='message_server_api.add_message_request.client_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='message_server_api.add_message_request.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=200,
)


_ADD_MESSAGE_RESPONSE = _descriptor.Descriptor(
  name='add_message_response',
  full_name='message_server_api.add_message_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_id', full_name='message_server_api.add_message_response.message_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=244,
)


_POLL_MESSAGE_REQUEST = _descriptor.Descriptor(
  name='poll_message_request',
  full_name='message_server_api.poll_message_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='last_polled_message_id', full_name='message_server_api.poll_message_request.last_polled_message_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_id', full_name='message_server_api.poll_message_request.client_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=319,
)


_POLL_MESSAGE_RESPONSE = _descriptor.Descriptor(
  name='poll_message_response',
  full_name='message_server_api.poll_message_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='message_server_api.poll_message_response.text', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message_id', full_name='message_server_api.poll_message_response.message_id', index=1,
      number=2, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_id', full_name='message_server_api.poll_message_response.client_id', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=321,
  serialized_end=397,
)

DESCRIPTOR.message_types_by_name['register_client_request'] = _REGISTER_CLIENT_REQUEST
DESCRIPTOR.message_types_by_name['register_client_response'] = _REGISTER_CLIENT_RESPONSE
DESCRIPTOR.message_types_by_name['add_message_request'] = _ADD_MESSAGE_REQUEST
DESCRIPTOR.message_types_by_name['add_message_response'] = _ADD_MESSAGE_RESPONSE
DESCRIPTOR.message_types_by_name['poll_message_request'] = _POLL_MESSAGE_REQUEST
DESCRIPTOR.message_types_by_name['poll_message_response'] = _POLL_MESSAGE_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

register_client_request = _reflection.GeneratedProtocolMessageType('register_client_request', (_message.Message,), {
  'DESCRIPTOR' : _REGISTER_CLIENT_REQUEST,
  '__module__' : 'message_server_pb2'
  # @@protoc_insertion_point(class_scope:message_server_api.register_client_request)
  })
_sym_db.RegisterMessage(register_client_request)

register_client_response = _reflection.GeneratedProtocolMessageType('register_client_response', (_message.Message,), {
  'DESCRIPTOR' : _REGISTER_CLIENT_RESPONSE,
  '__module__' : 'message_server_pb2'
  # @@protoc_insertion_point(class_scope:message_server_api.register_client_response)
  })
_sym_db.RegisterMessage(register_client_response)

add_message_request = _reflection.GeneratedProtocolMessageType('add_message_request', (_message.Message,), {
  'DESCRIPTOR' : _ADD_MESSAGE_REQUEST,
  '__module__' : 'message_server_pb2'
  # @@protoc_insertion_point(class_scope:message_server_api.add_message_request)
  })
_sym_db.RegisterMessage(add_message_request)

add_message_response = _reflection.GeneratedProtocolMessageType('add_message_response', (_message.Message,), {
  'DESCRIPTOR' : _ADD_MESSAGE_RESPONSE,
  '__module__' : 'message_server_pb2'
  # @@protoc_insertion_point(class_scope:message_server_api.add_message_response)
  })
_sym_db.RegisterMessage(add_message_response)

poll_message_request = _reflection.GeneratedProtocolMessageType('poll_message_request', (_message.Message,), {
  'DESCRIPTOR' : _POLL_MESSAGE_REQUEST,
  '__module__' : 'message_server_pb2'
  # @@protoc_insertion_point(class_scope:message_server_api.poll_message_request)
  })
_sym_db.RegisterMessage(poll_message_request)

poll_message_response = _reflection.GeneratedProtocolMessageType('poll_message_response', (_message.Message,), {
  'DESCRIPTOR' : _POLL_MESSAGE_RESPONSE,
  '__module__' : 'message_server_pb2'
  # @@protoc_insertion_point(class_scope:message_server_api.poll_message_response)
  })
_sym_db.RegisterMessage(poll_message_response)



_STORAGE = _descriptor.ServiceDescriptor(
  name='storage',
  full_name='message_server_api.storage',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=400,
  serialized_end=724,
  methods=[
  _descriptor.MethodDescriptor(
    name='add_message',
    full_name='message_server_api.storage.add_message',
    index=0,
    containing_service=None,
    input_type=_ADD_MESSAGE_REQUEST,
    output_type=_ADD_MESSAGE_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='poll_message',
    full_name='message_server_api.storage.poll_message',
    index=1,
    containing_service=None,
    input_type=_POLL_MESSAGE_REQUEST,
    output_type=_POLL_MESSAGE_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='register_client',
    full_name='message_server_api.storage.register_client',
    index=2,
    containing_service=None,
    input_type=_REGISTER_CLIENT_REQUEST,
    output_type=_REGISTER_CLIENT_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STORAGE)

DESCRIPTOR.services_by_name['storage'] = _STORAGE

# @@protoc_insertion_point(module_scope)
