// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: message_server.proto
#ifndef GRPC_message_5fserver_2eproto__INCLUDED
#define GRPC_message_5fserver_2eproto__INCLUDED

#include "message_server.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace message_server_api {

class storage final {
 public:
  static constexpr char const* service_full_name() {
    return "message_server_api.storage";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status add_message(::grpc::ClientContext* context, const ::message_server_api::add_message_request& request, ::message_server_api::add_message_response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::message_server_api::add_message_response>> Asyncadd_message(::grpc::ClientContext* context, const ::message_server_api::add_message_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::message_server_api::add_message_response>>(Asyncadd_messageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::message_server_api::add_message_response>> PrepareAsyncadd_message(::grpc::ClientContext* context, const ::message_server_api::add_message_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::message_server_api::add_message_response>>(PrepareAsyncadd_messageRaw(context, request, cq));
    }
    virtual ::grpc::Status poll_message(::grpc::ClientContext* context, const ::message_server_api::poll_message_request& request, ::message_server_api::poll_message_response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::message_server_api::poll_message_response>> Asyncpoll_message(::grpc::ClientContext* context, const ::message_server_api::poll_message_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::message_server_api::poll_message_response>>(Asyncpoll_messageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::message_server_api::poll_message_response>> PrepareAsyncpoll_message(::grpc::ClientContext* context, const ::message_server_api::poll_message_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::message_server_api::poll_message_response>>(PrepareAsyncpoll_messageRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void add_message(::grpc::ClientContext* context, const ::message_server_api::add_message_request* request, ::message_server_api::add_message_response* response, std::function<void(::grpc::Status)>) = 0;
      virtual void add_message(::grpc::ClientContext* context, const ::message_server_api::add_message_request* request, ::message_server_api::add_message_response* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void poll_message(::grpc::ClientContext* context, const ::message_server_api::poll_message_request* request, ::message_server_api::poll_message_response* response, std::function<void(::grpc::Status)>) = 0;
      virtual void poll_message(::grpc::ClientContext* context, const ::message_server_api::poll_message_request* request, ::message_server_api::poll_message_response* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::message_server_api::add_message_response>* Asyncadd_messageRaw(::grpc::ClientContext* context, const ::message_server_api::add_message_request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::message_server_api::add_message_response>* PrepareAsyncadd_messageRaw(::grpc::ClientContext* context, const ::message_server_api::add_message_request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::message_server_api::poll_message_response>* Asyncpoll_messageRaw(::grpc::ClientContext* context, const ::message_server_api::poll_message_request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::message_server_api::poll_message_response>* PrepareAsyncpoll_messageRaw(::grpc::ClientContext* context, const ::message_server_api::poll_message_request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status add_message(::grpc::ClientContext* context, const ::message_server_api::add_message_request& request, ::message_server_api::add_message_response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::message_server_api::add_message_response>> Asyncadd_message(::grpc::ClientContext* context, const ::message_server_api::add_message_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::message_server_api::add_message_response>>(Asyncadd_messageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::message_server_api::add_message_response>> PrepareAsyncadd_message(::grpc::ClientContext* context, const ::message_server_api::add_message_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::message_server_api::add_message_response>>(PrepareAsyncadd_messageRaw(context, request, cq));
    }
    ::grpc::Status poll_message(::grpc::ClientContext* context, const ::message_server_api::poll_message_request& request, ::message_server_api::poll_message_response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::message_server_api::poll_message_response>> Asyncpoll_message(::grpc::ClientContext* context, const ::message_server_api::poll_message_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::message_server_api::poll_message_response>>(Asyncpoll_messageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::message_server_api::poll_message_response>> PrepareAsyncpoll_message(::grpc::ClientContext* context, const ::message_server_api::poll_message_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::message_server_api::poll_message_response>>(PrepareAsyncpoll_messageRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void add_message(::grpc::ClientContext* context, const ::message_server_api::add_message_request* request, ::message_server_api::add_message_response* response, std::function<void(::grpc::Status)>) override;
      void add_message(::grpc::ClientContext* context, const ::message_server_api::add_message_request* request, ::message_server_api::add_message_response* response, ::grpc::ClientUnaryReactor* reactor) override;
      void poll_message(::grpc::ClientContext* context, const ::message_server_api::poll_message_request* request, ::message_server_api::poll_message_response* response, std::function<void(::grpc::Status)>) override;
      void poll_message(::grpc::ClientContext* context, const ::message_server_api::poll_message_request* request, ::message_server_api::poll_message_response* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::message_server_api::add_message_response>* Asyncadd_messageRaw(::grpc::ClientContext* context, const ::message_server_api::add_message_request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::message_server_api::add_message_response>* PrepareAsyncadd_messageRaw(::grpc::ClientContext* context, const ::message_server_api::add_message_request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::message_server_api::poll_message_response>* Asyncpoll_messageRaw(::grpc::ClientContext* context, const ::message_server_api::poll_message_request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::message_server_api::poll_message_response>* PrepareAsyncpoll_messageRaw(::grpc::ClientContext* context, const ::message_server_api::poll_message_request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_add_message_;
    const ::grpc::internal::RpcMethod rpcmethod_poll_message_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status add_message(::grpc::ServerContext* context, const ::message_server_api::add_message_request* request, ::message_server_api::add_message_response* response);
    virtual ::grpc::Status poll_message(::grpc::ServerContext* context, const ::message_server_api::poll_message_request* request, ::message_server_api::poll_message_response* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_add_message : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_add_message() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_add_message() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status add_message(::grpc::ServerContext* /*context*/, const ::message_server_api::add_message_request* /*request*/, ::message_server_api::add_message_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestadd_message(::grpc::ServerContext* context, ::message_server_api::add_message_request* request, ::grpc::ServerAsyncResponseWriter< ::message_server_api::add_message_response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_poll_message : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_poll_message() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_poll_message() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status poll_message(::grpc::ServerContext* /*context*/, const ::message_server_api::poll_message_request* /*request*/, ::message_server_api::poll_message_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestpoll_message(::grpc::ServerContext* context, ::message_server_api::poll_message_request* request, ::grpc::ServerAsyncResponseWriter< ::message_server_api::poll_message_response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_add_message<WithAsyncMethod_poll_message<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_add_message : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_add_message() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::message_server_api::add_message_request, ::message_server_api::add_message_response>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::message_server_api::add_message_request* request, ::message_server_api::add_message_response* response) { return this->add_message(context, request, response); }));}
    void SetMessageAllocatorFor_add_message(
        ::grpc::MessageAllocator< ::message_server_api::add_message_request, ::message_server_api::add_message_response>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::message_server_api::add_message_request, ::message_server_api::add_message_response>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_add_message() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status add_message(::grpc::ServerContext* /*context*/, const ::message_server_api::add_message_request* /*request*/, ::message_server_api::add_message_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* add_message(
      ::grpc::CallbackServerContext* /*context*/, const ::message_server_api::add_message_request* /*request*/, ::message_server_api::add_message_response* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_poll_message : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_poll_message() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::message_server_api::poll_message_request, ::message_server_api::poll_message_response>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::message_server_api::poll_message_request* request, ::message_server_api::poll_message_response* response) { return this->poll_message(context, request, response); }));}
    void SetMessageAllocatorFor_poll_message(
        ::grpc::MessageAllocator< ::message_server_api::poll_message_request, ::message_server_api::poll_message_response>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::message_server_api::poll_message_request, ::message_server_api::poll_message_response>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_poll_message() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status poll_message(::grpc::ServerContext* /*context*/, const ::message_server_api::poll_message_request* /*request*/, ::message_server_api::poll_message_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* poll_message(
      ::grpc::CallbackServerContext* /*context*/, const ::message_server_api::poll_message_request* /*request*/, ::message_server_api::poll_message_response* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_add_message<WithCallbackMethod_poll_message<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_add_message : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_add_message() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_add_message() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status add_message(::grpc::ServerContext* /*context*/, const ::message_server_api::add_message_request* /*request*/, ::message_server_api::add_message_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_poll_message : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_poll_message() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_poll_message() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status poll_message(::grpc::ServerContext* /*context*/, const ::message_server_api::poll_message_request* /*request*/, ::message_server_api::poll_message_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_add_message : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_add_message() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_add_message() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status add_message(::grpc::ServerContext* /*context*/, const ::message_server_api::add_message_request* /*request*/, ::message_server_api::add_message_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestadd_message(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_poll_message : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_poll_message() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_poll_message() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status poll_message(::grpc::ServerContext* /*context*/, const ::message_server_api::poll_message_request* /*request*/, ::message_server_api::poll_message_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestpoll_message(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_add_message : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_add_message() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->add_message(context, request, response); }));
    }
    ~WithRawCallbackMethod_add_message() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status add_message(::grpc::ServerContext* /*context*/, const ::message_server_api::add_message_request* /*request*/, ::message_server_api::add_message_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* add_message(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_poll_message : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_poll_message() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->poll_message(context, request, response); }));
    }
    ~WithRawCallbackMethod_poll_message() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status poll_message(::grpc::ServerContext* /*context*/, const ::message_server_api::poll_message_request* /*request*/, ::message_server_api::poll_message_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* poll_message(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_add_message : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_add_message() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::message_server_api::add_message_request, ::message_server_api::add_message_response>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::message_server_api::add_message_request, ::message_server_api::add_message_response>* streamer) {
                       return this->Streamedadd_message(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_add_message() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status add_message(::grpc::ServerContext* /*context*/, const ::message_server_api::add_message_request* /*request*/, ::message_server_api::add_message_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedadd_message(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::message_server_api::add_message_request,::message_server_api::add_message_response>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_poll_message : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_poll_message() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::message_server_api::poll_message_request, ::message_server_api::poll_message_response>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::message_server_api::poll_message_request, ::message_server_api::poll_message_response>* streamer) {
                       return this->Streamedpoll_message(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_poll_message() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status poll_message(::grpc::ServerContext* /*context*/, const ::message_server_api::poll_message_request* /*request*/, ::message_server_api::poll_message_response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedpoll_message(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::message_server_api::poll_message_request,::message_server_api::poll_message_response>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_add_message<WithStreamedUnaryMethod_poll_message<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_add_message<WithStreamedUnaryMethod_poll_message<Service > > StreamedService;
};

}  // namespace message_server_api


#endif  // GRPC_message_5fserver_2eproto__INCLUDED
